version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/task-todo/api
    depends_on:
      - mysql
      - phpmyadmin
      - api
    restart: always
  api:
    build: ./__docker/php
    volumes:
      - ./api:/var/www/task-todo/api
    restart: always
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./api/db:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9999:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
  composer:
    image: composer:latest
    volumes:
      - ./api:/var/www/task-todo/api
    working_dir: /var/www/task-todo/api
    user: "1000:1000"
    entrypoint: ["composer"]
